### ISSUE TITLE
Ores Regenerating too quick

### ISSUE THREAD

**Issue by Fir3will** [Dylan-ForgeMods/RegenOres#2]
I don't think this might always be an issue but for most of your dormant blocks. You have the time to wait:
int lol = par5Random.nextInt(RegenOres_Main.BlockChance);
I personally think you should change this to:
int lol = RegenOres_Main.BlockChance / 2 + par5Random.nextInt(RegenOres_Main.BlockChance / 2);
Just so you don't have ores regenerating too quick. Just a suggestion really, not a issue.

**Comment by dylanpdx** [comment]
Revival version fixed this issue
