### ISSUE TITLE
TileEntities Returning Null

### ISSUE THREAD

**Issue by Fir3will** [Dylan-ForgeMods/RegenOres#3]
I don't know why you did this but, most of the dormant blocks have a tile entity that returns null. I personally suggest that you use tile entities to actually regenerate the ore. In the tile entity class, you can have all the regeneration code in the update entity. This will make it easier. I believe this because I personally had some bad experiences with using the block's update methods. If you need more insight on this, feel free to let me know! I'll even write all the code for you!

**Comment by dylanpdx** [comment]
Revival version fixed this issue
